version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      AUTH_TOKEN: ${AUTH_TOKEN}
    depends_on:
      - redis
  redis:
    image: "redis:6.2.3-alpine"
